name: build
on:
  push
  
jobs:
  security-scanning:
    uses: DavinciLisapaly/InfrastructureDemo/.github/workflows/security-scans.yml@main
    permissions:
      security-events: write
      contents: read # only needed for private or internal repos
      actions: read # only needed for private or internal repos
      
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write

    steps:
      - uses: actions/checkout@v4
      - name: Build (dummy)
        run: 

  build-and-push-image:
    needs: [build-and-test]
    runs-on: ubuntu-latest 
    permissions:
      contents: write 
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Build (dummy)
        run: 
                 
  deploy:
      needs: [build-and-push-image, security-scanning]
      runs-on: ubuntu-latest
      permissions:
        contents: write
        packages: write

      steps:  
        - uses: actions/checkout@v4
        - name: Build (dummy)
          run: 
